Repository smruti-banty/library-management, pull requests merged in 2023-10, with the labels that each got.

#16 axios, react-icons, react-router add
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/index.css
  frontend/tailwind.config.js
Labels: documentation

#28 23 define notification domain
  backend/src/main/java/com/lms/backend/constants/NotificationStatus.java
  backend/src/main/java/com/lms/backend/dto/NotificationRequestDto.java
  backend/src/main/java/com/lms/backend/model/Notification.java
  backend/src/main/java/com/lms/backend/repository/NotificationRepository.java
Labels: enhancement

#32 31 notification field addition
  backend/src/main/java/com/lms/backend/constants/NotificationStateStatus.java
  backend/src/main/java/com/lms/backend/model/Notification.java
Labels: bug

#40 39 notification id read status bug fix
  backend/src/main/java/com/lms/backend/constants/NotificationStateStatus.java
  backend/src/main/java/com/lms/backend/dto/NotificationRequestDto.java
  backend/src/main/java/com/lms/backend/model/Notification.java
  backend/src/main/java/com/lms/backend/repository/NotificationRepository.java
  backend/src/main/java/com/lms/backend/services/NotificationService.java
  backend/src/main/java/com/lms/backend/services/impl/NotificationImpl.java
Labels: bug

#42 41 create notification controller
  backend/src/main/java/com/lms/backend/controller/NotificationController.java
  backend/src/main/java/com/lms/backend/repository/NotificationRepository.java
  backend/src/main/java/com/lms/backend/services/NotificationService.java
  backend/src/main/java/com/lms/backend/services/impl/NotificationImpl.java
Labels: enhancement

#52 extra method remove from repository
  backend/src/main/java/com/lms/backend/repository/NotificationRepository.java
Labels: bug

#54 enum filed in BookIssue model add
  backend/src/main/java/com/lms/backend/model/BookIssue.java
Labels: bug

#57 56 create book issue controller
  backend/src/main/java/com/lms/backend/controller/BookIssueController.java
  backend/src/main/java/com/lms/backend/repository/BookIssueRepository.java
  backend/src/main/java/com/lms/backend/services/BookIssueService.java
  backend/src/main/java/com/lms/backend/services/impl/BookIssueServiceImpl.java
Labels: enhancement

#55 48 create service for issue book
  backend/src/main/java/com/lms/backend/repository/BookIssueRepository.java
  backend/src/main/java/com/lms/backend/services/BookIssueService.java
  backend/src/main/java/com/lms/backend/services/impl/BookIssueServiceImpl.java
Labels: enhancement

#68 bookissue to book/issue change
  backend/src/main/java/com/lms/backend/controller/BookIssueController.java
Labels: bug

#73 72 create service and controller for transaction
  backend/src/main/java/com/lms/backend/model/Transaction.java
  backend/src/main/java/com/lms/backend/repository/TransactionRepository.java
  backend/src/main/java/com/lms/backend/services/TransactionService.java
  backend/src/main/java/com/lms/backend/services/impl/BookIssueServiceImpl.java
  backend/src/main/java/com/lms/backend/services/impl/TransactionServiceImpl.java
Labels: enhancement

#69 64 mark book as out of stock
  backend/src/main/java/com/lms/backend/controller/BookController.java
  backend/src/main/java/com/lms/backend/services/BookService.java
  backend/src/main/java/com/lms/backend/services/impl/BookServiceImpl.java
Labels: enhancement

#75 stock manage for book add
  backend/src/main/java/com/lms/backend/services/impl/BookIssueServiceImpl.java
Labels: enhancement

#80 issue book restriction add
  backend/src/main/java/com/lms/backend/services/impl/BookIssueServiceImpl.java
Labels: bug
